name: Validate Schema
on: [push, pull_request]
jobs:
  Run-Validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Fetch the repository
      - name: Identify changed YAML files
        run: | # Example Bash script
          changed_files=$(git diff --name-only HEAD~ HEAD)
          yaml_files=$(echo "$changed_files" | grep -E '\.ya?ml$')
          echo "YAML_FILES=$yaml_files" >> $GITHUB_ENV  # Store filtered files in environment variable
      - uses: nrkno/yaml-schema-validator-github-action@v4
        with:
          schema: schemas/schema.yaml
          target: ${{ env.YAML_FILES }}
